#ifndef __ARM64_MACHINE_ENDIAN_H_
#define __ARM64_MACHINE_ENDIAN_H_

#if __AARCH64EB__
#define __BYTE_ORDER __BIG_ENDIAN
#else
#define __BYTE_ORDER __LITTLE_ENDIAN
#endif

#endif //__ARM_MACHINE_ENDIAN_H_
