#!groovy
@Library('jenkins-pipeline-lib') _

pipeline
{
  agent any
  stages
  {
    stage('Setup')
    {
      steps
      {
        sh 'make clean'
      }
    }
    stage('Build')
    {
      steps
      {
        sh 'make'
      }
    }
    stage('Archive')
    {
      steps
      {
        echo 'Archiving artifacts'
        archiveArtifacts 'buildresults/**/*'
      }
      post
      {
        failure
        {
          sendNotifications 'ARCHIVE_ERROR'
        }
      }
    }
  }
  post
  {
    always
    {
      sendNotifications(currentBuild.result,currentBuild.changeSets)
    }
    failure
    {
      /*
      * This job does not have a GitHub configuration,
      * so we need to create a dummy config
      */
      githubSetConfig('4c01f168-ca25-483e-bc6d-8d105fc5fb70')
      githubFileIssue()
    }
  }
}
