pipeline
{
  agent any
  stages
  {
    stage('Setup')
    {
      steps
      {
        sh 'make clean'
      }
    }
    stage('Build')
    {
      steps
      {
        sh 'make'
      }
    }
    stage('Archive')
    {
      steps
      {
        archiveArtifacts 'buildresults/**/*'
      }
      post
      {
        failure
        {
          slackSend(message: "${env.JOB_NAME} #${env.BUILD_NUMBER}: Archiving Error (<${env.BUILD_URL}|Open>)", botUser: true, channel: '#sw-notify', color: 'F13C15')
        }
      }
    }
  }
  post
  {
    success
    {
      slackSend(message: "${env.JOB_NAME} #${env.BUILD_NUMBER}: Successful (<${env.BUILD_URL}|Open>)", botUser: true, channel: '#sw-notify', color: '#27AE60')
    }
    failure
    {
      slackSend(message: "${env.JOB_NAME} #${env.BUILD_NUMBER}: FAILED! (<${env.BUILD_URL}|Open>)", botUser: true, channel: '#sw-notify', color: '#E74C3C')
    }
    aborted
    {
      slackSend(message: "${env.JOB_NAME} #${env.BUILD_NUMBER}: Aborted (<${env.BUILD_URL}|Open>)", botUser: true, channel: '#sw-notify', color: '#D7DBDD')
    }
  }
}
